version: '3'
services:
  
  app:
    container_name: multiContianerDemoFlaskStorage
    build: ./app
    restart: always
    links: - db
    ports: - "5000:5000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: student_vaccination
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
    depends_on:
      - db

volumes:
  - ./db/:/docker-entrypoint-initdb.d/:ro
