FROM python:3.9

RUN python3 -m pip install --upgrade pip
RUN pip3 install flask
RUN pip3 install mysql-connector-python
RUN pip install -r requirements.txt 

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY templates /app/templates
COPY static /app/static
COPY app.py /app

EXPOSE 5000